<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
class BsBlockMuncCorpMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        $data = [
            [ 'id' => 119, 'district_id' => 17, 'subdivision_id' => 34, 'schcd' => '191018', 'name' => 'NABADWIP MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 121, 'district_id' => 17, 'subdivision_id' => 31, 'schcd' => '191024', 'name' => 'GAYESHPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 122, 'district_id' => 17, 'subdivision_id' => 31, 'schcd' => '191023', 'name' => 'KALYANI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 128, 'district_id' => 17, 'subdivision_id' => 32, 'schcd' => '191020', 'name' => 'RANAGHAT MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 131, 'district_id' => 17, 'subdivision_id' => 34, 'schcd' => '191019', 'name' => 'KRISHNAGAR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 134, 'district_id' => 17, 'subdivision_id' => 32, 'schcd' => '191022', 'name' => 'BIRNAGAR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 135, 'district_id' => 17, 'subdivision_id' => 32, 'schcd' => '191021', 'name' => 'SANTIPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 136, 'district_id' => 17, 'subdivision_id' => 31, 'schcd' => '191028', 'name' => 'HARINGHATA Municipality', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 532, 'district_id' => 21, 'subdivision_id' => 1, 'schcd' => '190130', 'name' => 'RANGLI RANGLIOT', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 533, 'district_id' => 17, 'subdivision_id' => null, 'schcd' => '191029', 'name' => 'KALYANI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 534, 'district_id' => 15, 'subdivision_id' => null, 'schcd' => '192215', 'name' => 'Falakata Municipality', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 535, 'district_id' => 2, 'subdivision_id' => null, 'schcd' => '190219', 'name' => 'KRANTI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 536, 'district_id' => 2, 'subdivision_id' => null, 'schcd' => '190220', 'name' => 'BANARHAT', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 538, 'district_id' => 7, 'subdivision_id' => null, 'schcd' => '289244', 'name' => 'BUNIYADPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 104, 'district_id' => 18, 'subdivision_id' => 53, 'schcd' => '191835', 'name' => 'PUJALI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 105, 'district_id' => 18, 'subdivision_id' => 57, 'schcd' => '191830', 'name' => 'BARUIPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 106, 'district_id' => 18, 'subdivision_id' => 57, 'schcd' => '191836', 'name' => 'RAJPUR SONARPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 141, 'district_id' => 18, 'subdivision_id' => 54, 'schcd' => '191832', 'name' => 'DIAMOND HARBOUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 192, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191123', 'name' => 'BARASAT MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 193, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191124', 'name' => 'HABRA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 194, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191125', 'name' => 'ASHOKENAGAR-KALYANGARH MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 195, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191126', 'name' => 'MADHYAMGRAM MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 222, 'district_id' => 19, 'subdivision_id' => 24, 'schcd' => '190821', 'name' => 'SURI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 223, 'district_id' => 19, 'subdivision_id' => 24, 'schcd' => '190822', 'name' => 'SAINTHIA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 224, 'district_id' => 19, 'subdivision_id' => 24, 'schcd' => '190823', 'name' => 'DUBRAJPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 225, 'district_id' => 19, 'subdivision_id' => 23, 'schcd' => '190824', 'name' => 'RAMPURHAT MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 226, 'district_id' => 19, 'subdivision_id' => 23, 'schcd' => '190825', 'name' => 'NALHATI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 230, 'district_id' => 15, 'subdivision_id' => 68, 'schcd' => '192214', 'name' => 'ALIPURDUAR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 239, 'district_id' => 2, 'subdivision_id' => 5, 'schcd' => '190216', 'name' => 'MAL MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 238, 'district_id' => 2, 'subdivision_id' => 4, 'schcd' => '190215', 'name' => 'JALPAIGURI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 242, 'district_id' => 2, 'subdivision_id' => 4, 'schcd' => '190218', 'name' => 'DHUPGURI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 274, 'district_id' => 14, 'subdivision_id' => 60, 'schcd' => '191926', 'name' => 'HALDIA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 167, 'district_id' => 25, 'subdivision_id' => 26, 'schcd' => '192601', 'name' => 'ANDAL', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 168, 'district_id' => 25, 'subdivision_id' => 25, 'schcd' => '192602', 'name' => 'BARABANI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 169, 'district_id' => 25, 'subdivision_id' => 26, 'schcd' => '192603', 'name' => 'DURGAPUR-FARIDPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 170, 'district_id' => 25, 'subdivision_id' => 25, 'schcd' => '192604', 'name' => 'JAMURIA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 171, 'district_id' => 25, 'subdivision_id' => 26, 'schcd' => '192605', 'name' => 'KANKSA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 172, 'district_id' => 25, 'subdivision_id' => 26, 'schcd' => '192606', 'name' => 'PANDABESWAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 173, 'district_id' => 25, 'subdivision_id' => 25, 'schcd' => '192607', 'name' => 'RANIGANJ', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 174, 'district_id' => 25, 'subdivision_id' => 25, 'schcd' => '192608', 'name' => 'SALANPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 411, 'district_id' => 5, 'subdivision_id' => 18, 'schcd' => '190734', 'name' => 'DOMKAL (M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 440, 'district_id' => 22, 'subdivision_id' => 65, 'schcd' => '192036', 'name' => 'CHANDRAKONA(MN)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 441, 'district_id' => 22, 'subdivision_id' => 65, 'schcd' => '192037', 'name' => 'RAMJIBANPUR(MN)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 461, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190617', 'name' => 'OLD MALDA(MNC)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 435, 'district_id' => 22, 'subdivision_id' => 66, 'schcd' => '192030', 'name' => 'MIDNAPORE(MN)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 436, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192031', 'name' => 'KHARAGPUR(MN)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 437, 'district_id' => 22, 'subdivision_id' => 65, 'schcd' => '192032', 'name' => 'GHATAL(MN)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 438, 'district_id' => 22, 'subdivision_id' => 65, 'schcd' => '192034', 'name' => 'KHARAR(MN)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 439, 'district_id' => 22, 'subdivision_id' => 65, 'schcd' => '192035', 'name' => 'KHIRPAI(MN)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 341, 'district_id' => 3, 'subdivision_id' => 29, 'schcd' => '192505', 'name' => 'BURDWAN-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 478, 'district_id' => 12, 'subdivision_id' => 67, 'schcd' => '192105', 'name' => 'SILIGURI MUNICIPAL CORPORATION', 'type' => 'C', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 342, 'district_id' => 3, 'subdivision_id' => 29, 'schcd' => '192506', 'name' => 'GALSI-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 340, 'district_id' => 3, 'subdivision_id' => 29, 'schcd' => '192504', 'name' => 'BURDWAN-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 339, 'district_id' => 3, 'subdivision_id' => 29, 'schcd' => '192503', 'name' => 'BHATAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 303, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191146', 'name' => 'BASIRHAT MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 186, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191117', 'name' => 'SANDESHKHALI - I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 187, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191118', 'name' => 'SANDESHKHALI - II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 304, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191147', 'name' => 'BADURIA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 305, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191148', 'name' => 'TAKI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 306, 'district_id' => 23, 'subdivision_id' => 39, 'schcd' => '191149', 'name' => 'BONGAON MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 329, 'district_id' => 4, 'subdivision_id' => 45, 'schcd' => '191324', 'name' => 'BISHNUPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 275, 'district_id' => 14, 'subdivision_id' => 61, 'schcd' => '191927', 'name' => 'TAMLUK MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 276, 'district_id' => 14, 'subdivision_id' => 59, 'schcd' => '191928', 'name' => 'EGRA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 277, 'district_id' => 14, 'subdivision_id' => 58, 'schcd' => '191929', 'name' => 'CONTAI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 279, 'district_id' => 14, 'subdivision_id' => 61, 'schcd' => '191931', 'name' => 'PANSKURA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 289, 'district_id' => 20, 'subdivision_id' => 50, 'schcd' => '191616', 'name' => 'BALLY MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 290, 'district_id' => 20, 'subdivision_id' => 51, 'schcd' => '191617', 'name' => 'ULUBERIA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 337, 'district_id' => 3, 'subdivision_id' => 29, 'schcd' => '192501', 'name' => 'AUSGRAM-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 446, 'district_id' => 8, 'subdivision_id' => 63, 'schcd' => '192308', 'name' => 'JHARGRAM(MN)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 338, 'district_id' => 3, 'subdivision_id' => 29, 'schcd' => '192502', 'name' => 'AUSGRAM-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 331, 'district_id' => 4, 'subdivision_id' => 45, 'schcd' => '191325', 'name' => 'SONAMUKHI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 333, 'district_id' => 4, 'subdivision_id' => 44, 'schcd' => '191323', 'name' => 'BANKURA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            // [ 'id' => 511, 'district_id' => 13, 'subdivision_id' => 71, 'schcd' => '191421', 'name' => 'PURULIA(M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 512, 'district_id' => 13, 'subdivision_id' => 47, 'schcd' => '191422', 'name' => 'RAGHUNATHPUR(M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 513, 'district_id' => 13, 'subdivision_id' => 49, 'schcd' => '191423', 'name' => 'JHALDA(M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 509, 'district_id' => 13, 'subdivision_id' => 47, 'schcd' => '191419', 'name' => 'RAGHUNTHPUR-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 510, 'district_id' => 13, 'subdivision_id' => 47, 'schcd' => '191420', 'name' => 'SANTURI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 514, 'district_id' => 6, 'subdivision_id' => 6, 'schcd' => '190301', 'name' => 'DINHATA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 515, 'district_id' => 6, 'subdivision_id' => 6, 'schcd' => '190302', 'name' => 'DINHATA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 516, 'district_id' => 6, 'subdivision_id' => 6, 'schcd' => '190303', 'name' => 'SITAI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 517, 'district_id' => 6, 'subdivision_id' => 10, 'schcd' => '190304', 'name' => 'TUFANGANJ-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 23, 'district_id' => 1, 'subdivision_id' => 42, 'schcd' => '191219', 'name' => 'HOOGHLY-CHINSURAH MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 489, 'district_id' => 10, 'subdivision_id' => 12, 'schcd' => '190410', 'name' => 'KALIYAGANJ MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 490, 'district_id' => 10, 'subdivision_id' => 12, 'schcd' => '190411', 'name' => 'RAIGANJ MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 491, 'district_id' => 10, 'subdivision_id' => 11, 'schcd' => '190412', 'name' => 'ISLAMPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 492, 'district_id' => 10, 'subdivision_id' => 11, 'schcd' => '190413', 'name' => 'DALKHOLA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 526, 'district_id' => 6, 'subdivision_id' => 6, 'schcd' => '190313', 'name' => 'DINHATA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 527, 'district_id' => 6, 'subdivision_id' => 10, 'schcd' => '190314', 'name' => 'TUFANGANJ MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 528, 'district_id' => 6, 'subdivision_id' => 9, 'schcd' => '190315', 'name' => 'MEKHLIGANJ MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 529, 'district_id' => 6, 'subdivision_id' => 9, 'schcd' => '190316', 'name' => 'HALDIBARI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 530, 'district_id' => 6, 'subdivision_id' => 7, 'schcd' => '190317', 'name' => 'COOCH BEHAR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 531, 'district_id' => 6, 'subdivision_id' => 8, 'schcd' => '190318', 'name' => 'MATHABHANGA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 473, 'district_id' => 11, 'subdivision_id' => 52, 'schcd' => '191701', 'name' => 'KOLKATA MUNICIPAL CORPORATION', 'type' => 'C', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 453, 'district_id' => 21, 'subdivision_id' => 1, 'schcd' => '190137', 'name' => 'DARJEELING MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 454, 'district_id' => 21, 'subdivision_id' => 2, 'schcd' => '190139', 'name' => 'KURSEONG MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 455, 'district_id' => 21, 'subdivision_id' => 1, 'schcd' => '190140', 'name' => 'MIRIK MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 288, 'district_id' => 20, 'subdivision_id' => 50, 'schcd' => '191615', 'name' => 'HOWRAH MUNICIPAL CORPORATION', 'type' => 'C', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 270, 'district_id' => 14, 'subdivision_id' => 59, 'schcd' => '191922', 'name' => 'BHAGWANPUR -I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 271, 'district_id' => 14, 'subdivision_id' => 59, 'schcd' => '191923', 'name' => 'EGRA -I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 285, 'district_id' => 20, 'subdivision_id' => 50, 'schcd' => '191612', 'name' => 'PANCHLA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 286, 'district_id' => 20, 'subdivision_id' => 50, 'schcd' => '191613', 'name' => 'SANKRAIL', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 287, 'district_id' => 20, 'subdivision_id' => 50, 'schcd' => '191614', 'name' => 'DOMJUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 429, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192016', 'name' => 'KESHIARY', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 308, 'district_id' => 22, 'subdivision_id' => 66, 'schcd' => '192001', 'name' => 'MIDNAPORE SADAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 309, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191101', 'name' => 'AMDANGA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 314, 'district_id' => 4, 'subdivision_id' => 44, 'schcd' => '191301', 'name' => 'BANKURA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 315, 'district_id' => 4, 'subdivision_id' => 44, 'schcd' => '191303', 'name' => 'BARJORA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 316, 'district_id' => 4, 'subdivision_id' => 44, 'schcd' => '191305', 'name' => 'GANGAJAL GHATI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 317, 'district_id' => 4, 'subdivision_id' => 46, 'schcd' => '191307', 'name' => 'INDPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 318, 'district_id' => 4, 'subdivision_id' => 45, 'schcd' => '191308', 'name' => 'JOYPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 319, 'district_id' => 4, 'subdivision_id' => 45, 'schcd' => '191309', 'name' => 'KOTULPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 320, 'district_id' => 4, 'subdivision_id' => 46, 'schcd' => '191310', 'name' => 'KHATRA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 321, 'district_id' => 4, 'subdivision_id' => 46, 'schcd' => '191311', 'name' => 'HIRBANDH [KHATRA-II]', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 322, 'district_id' => 4, 'subdivision_id' => 44, 'schcd' => '191312', 'name' => 'MEJHIA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 323, 'district_id' => 7, 'subdivision_id' => 13, 'schcd' => '190501', 'name' => 'HILI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 363, 'district_id' => 3, 'subdivision_id' => 27, 'schcd' => '192527', 'name' => 'KALNA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 324, 'district_id' => 4, 'subdivision_id' => 45, 'schcd' => '191314', 'name' => 'PATRASAYER', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 325, 'district_id' => 4, 'subdivision_id' => 46, 'schcd' => '191315', 'name' => 'RANIBANDH', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 326, 'district_id' => 4, 'subdivision_id' => 46, 'schcd' => '191316', 'name' => 'RAIPUR-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 327, 'district_id' => 4, 'subdivision_id' => 46, 'schcd' => '191321', 'name' => 'TALDANGRA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 328, 'district_id' => 4, 'subdivision_id' => 45, 'schcd' => '191322', 'name' => 'BISHNUPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 93, 'district_id' => 18, 'subdivision_id' => 55, 'schcd' => '191810', 'name' => 'CANNING - 2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 94, 'district_id' => 18, 'subdivision_id' => 55, 'schcd' => '191814', 'name' => 'GOSABA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 95, 'district_id' => 18, 'subdivision_id' => 57, 'schcd' => '191815', 'name' => 'JOYNAGAR - 1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 96, 'district_id' => 18, 'subdivision_id' => 57, 'schcd' => '191816', 'name' => 'JOYNAGAR - 2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 97, 'district_id' => 18, 'subdivision_id' => 54, 'schcd' => '191818', 'name' => 'KULPI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 98, 'district_id' => 18, 'subdivision_id' => 57, 'schcd' => '191819', 'name' => 'KULTALI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 99, 'district_id' => 18, 'subdivision_id' => 54, 'schcd' => '191822', 'name' => 'MAGRAHAT - 2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 100, 'district_id' => 18, 'subdivision_id' => 54, 'schcd' => '191823', 'name' => 'MATHURAPUR - 1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 101, 'district_id' => 18, 'subdivision_id' => 56, 'schcd' => '191827', 'name' => 'SAGAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 107, 'district_id' => 18, 'subdivision_id' => 57, 'schcd' => '191801', 'name' => 'BARUIPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 108, 'district_id' => 18, 'subdivision_id' => 53, 'schcd' => '191829', 'name' => 'THAKURPUKUR MAHESHTALA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 109, 'district_id' => 17, 'subdivision_id' => 31, 'schcd' => '191017', 'name' => 'HARINGHATA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 111, 'district_id' => 17, 'subdivision_id' => 34, 'schcd' => '191005', 'name' => 'CHAPRA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 280, 'district_id' => 20, 'subdivision_id' => 51, 'schcd' => '191607', 'name' => 'ULUBERIA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 281, 'district_id' => 20, 'subdivision_id' => 51, 'schcd' => '191608', 'name' => 'UDAYNARAYANPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 282, 'district_id' => 20, 'subdivision_id' => 50, 'schcd' => '191609', 'name' => 'JAGATBALLAVPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 283, 'district_id' => 20, 'subdivision_id' => 51, 'schcd' => '191610', 'name' => 'SHYAMPUR-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 112, 'district_id' => 17, 'subdivision_id' => 34, 'schcd' => '191004', 'name' => 'KALIGANJ', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 113, 'district_id' => 17, 'subdivision_id' => 32, 'schcd' => '191015', 'name' => 'SANTIPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 114, 'district_id' => 17, 'subdivision_id' => 32, 'schcd' => '191012', 'name' => 'HANSKHALI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 115, 'district_id' => 17, 'subdivision_id' => 33, 'schcd' => '191011', 'name' => 'KARIMPUR - II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 374, 'district_id' => 7, 'subdivision_id' => 14, 'schcd' => '190509', 'name' => 'GANGARAMPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 375, 'district_id' => 7, 'subdivision_id' => 13, 'schcd' => '190510', 'name' => 'BALURGHAT MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 116, 'district_id' => 17, 'subdivision_id' => 32, 'schcd' => '191013', 'name' => 'RANAGHAT - I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 118, 'district_id' => 17, 'subdivision_id' => 33, 'schcd' => '191009', 'name' => 'TEHATTA - II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 123, 'district_id' => 17, 'subdivision_id' => 34, 'schcd' => '191006', 'name' => 'KRISHNAGANJ', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 124, 'district_id' => 17, 'subdivision_id' => 32, 'schcd' => '191014', 'name' => 'RANAGHAT - II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 125, 'district_id' => 17, 'subdivision_id' => 33, 'schcd' => '191010', 'name' => 'KARIMPUR - I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 126, 'district_id' => 17, 'subdivision_id' => 34, 'schcd' => '191001', 'name' => 'KRISHNAGAR - I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 127, 'district_id' => 17, 'subdivision_id' => 34, 'schcd' => '191003', 'name' => 'NAKASHIPARA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 129, 'district_id' => 17, 'subdivision_id' => 34, 'schcd' => '191002', 'name' => 'KRISHNAGAR - II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 404, 'district_id' => 5, 'subdivision_id' => 20, 'schcd' => '190727', 'name' => 'MURSHIDABAD (M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 405, 'district_id' => 5, 'subdivision_id' => 20, 'schcd' => '190728', 'name' => 'JIAGANJ-AZIMGANJ (M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 406, 'district_id' => 5, 'subdivision_id' => 18, 'schcd' => '190729', 'name' => 'DHULIYAN (M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 407, 'district_id' => 5, 'subdivision_id' => 21, 'schcd' => '190730', 'name' => 'BELDANGA (M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 408, 'district_id' => 5, 'subdivision_id' => 21, 'schcd' => '190731', 'name' => 'BERHAMPORE (M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 409, 'district_id' => 5, 'subdivision_id' => 19, 'schcd' => '190732', 'name' => 'KANDI (M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 410, 'district_id' => 5, 'subdivision_id' => 18, 'schcd' => '190733', 'name' => 'JANGIPUR (M)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 370, 'district_id' => 7, 'subdivision_id' => 14, 'schcd' => '190505', 'name' => 'BANSHIHARI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 371, 'district_id' => 7, 'subdivision_id' => 13, 'schcd' => '190506', 'name' => 'BALURGHAT', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 372, 'district_id' => 7, 'subdivision_id' => 13, 'schcd' => '190507', 'name' => 'TAPAN', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 130, 'district_id' => 17, 'subdivision_id' => 31, 'schcd' => '191016', 'name' => 'CHAKDAH', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 132, 'district_id' => 17, 'subdivision_id' => 34, 'schcd' => '191007', 'name' => 'NABADWIP', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 133, 'district_id' => 17, 'subdivision_id' => 33, 'schcd' => '191008', 'name' => 'TEHATTA - I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 140, 'district_id' => 18, 'subdivision_id' => 57, 'schcd' => '191828', 'name' => 'SONARPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 142, 'district_id' => 18, 'subdivision_id' => 54, 'schcd' => '191812', 'name' => 'DIAMOND HARBOUR - 2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 143, 'district_id' => 18, 'subdivision_id' => 56, 'schcd' => '191826', 'name' => 'PATHARPRATIMA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 157, 'district_id' => 18, 'subdivision_id' => 54, 'schcd' => '191824', 'name' => 'MATHURAPUR - 2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 158, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191102', 'name' => 'BARASAT - I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 159, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191103', 'name' => 'BARASAT - II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 160, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191104', 'name' => 'DEGANGA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 161, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191105', 'name' => 'HABRA - I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 162, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191106', 'name' => 'HABRA - II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 163, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191107', 'name' => 'RAJARHAT', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 166, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191110', 'name' => 'BADURIA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 117, 'district_id' => 17, 'subdivision_id' => 32, 'schcd' => '191027', 'name' => 'RANAGHAT COOPERS NAA', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 120, 'district_id' => 17, 'subdivision_id' => 32, 'schcd' => '191026', 'name' => 'TEHARPUR NAA', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 206, 'district_id' => 19, 'subdivision_id' => 24, 'schcd' => '190805', 'name' => 'SURI-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 207, 'district_id' => 19, 'subdivision_id' => 24, 'schcd' => '190806', 'name' => 'SURI-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 208, 'district_id' => 19, 'subdivision_id' => 24, 'schcd' => '190807', 'name' => 'SAINTHIA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 209, 'district_id' => 19, 'subdivision_id' => 24, 'schcd' => '190808', 'name' => 'MD. BAZAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 210, 'district_id' => 19, 'subdivision_id' => 24, 'schcd' => '190809', 'name' => 'RAJNAGAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 211, 'district_id' => 19, 'subdivision_id' => 24, 'schcd' => '190810', 'name' => 'DUBRAJPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 212, 'district_id' => 19, 'subdivision_id' => 24, 'schcd' => '190811', 'name' => 'KHOYRASOLE', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 213, 'district_id' => 19, 'subdivision_id' => 23, 'schcd' => '190812', 'name' => 'RAMPURHAT-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 364, 'district_id' => 3, 'subdivision_id' => 28, 'schcd' => '192528', 'name' => 'KATWA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 362, 'district_id' => 3, 'subdivision_id' => 29, 'schcd' => '192526', 'name' => 'GUSHKARA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 365, 'district_id' => 3, 'subdivision_id' => 30, 'schcd' => '192529', 'name' => 'MEMARI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 214, 'district_id' => 19, 'subdivision_id' => 23, 'schcd' => '190813', 'name' => 'RAMPURHAT-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 467, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190616', 'name' => 'ENGLISHBAZAR(MNC)', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 215, 'district_id' => 19, 'subdivision_id' => 23, 'schcd' => '190814', 'name' => 'MURARAI-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 216, 'district_id' => 19, 'subdivision_id' => 23, 'schcd' => '190815', 'name' => 'MURARAI-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 217, 'district_id' => 19, 'subdivision_id' => 23, 'schcd' => '190816', 'name' => 'NALHATI-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 218, 'district_id' => 19, 'subdivision_id' => 23, 'schcd' => '190817', 'name' => 'NALHATI-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 219, 'district_id' => 19, 'subdivision_id' => 23, 'schcd' => '190818', 'name' => 'MAYURESWAR-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 220, 'district_id' => 19, 'subdivision_id' => 23, 'schcd' => '190819', 'name' => 'MAYURESWAR-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 227, 'district_id' => 15, 'subdivision_id' => 68, 'schcd' => '192206', 'name' => 'KALCHINI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 228, 'district_id' => 15, 'subdivision_id' => 68, 'schcd' => '192207', 'name' => 'KUMARGRAM', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 229, 'district_id' => 15, 'subdivision_id' => 68, 'schcd' => '192208', 'name' => 'MADARIHAT', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 240, 'district_id' => 10, 'subdivision_id' => 11, 'schcd' => '190404', 'name' => 'GOALPOKHER - II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 243, 'district_id' => 19, 'subdivision_id' => 22, 'schcd' => '190801', 'name' => 'BOLPUR SRINIKETAN', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 244, 'district_id' => 20, 'subdivision_id' => 51, 'schcd' => '191601', 'name' => 'AMTA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 245, 'district_id' => 20, 'subdivision_id' => 51, 'schcd' => '191602', 'name' => 'AMTA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 246, 'district_id' => 20, 'subdivision_id' => 51, 'schcd' => '191603', 'name' => 'BAGNAN-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 247, 'district_id' => 20, 'subdivision_id' => 51, 'schcd' => '191604', 'name' => 'BAGNAN-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 248, 'district_id' => 20, 'subdivision_id' => 50, 'schcd' => '191605', 'name' => 'BALLY- JAGACHA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 249, 'district_id' => 14, 'subdivision_id' => 61, 'schcd' => '191901', 'name' => 'MOYNA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 250, 'district_id' => 14, 'subdivision_id' => 61, 'schcd' => '191902', 'name' => 'PANSKURA -II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 251, 'district_id' => 14, 'subdivision_id' => 61, 'schcd' => '191903', 'name' => 'PANSKURA -I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 233, 'district_id' => 2, 'subdivision_id' => 5, 'schcd' => '190209', 'name' => 'MAL', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 235, 'district_id' => 2, 'subdivision_id' => 4, 'schcd' => '190211', 'name' => 'MAYNAGURI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 237, 'district_id' => 2, 'subdivision_id' => 4, 'schcd' => '190213', 'name' => 'RAJGANJ', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 232, 'district_id' => 2, 'subdivision_id' => 4, 'schcd' => '190205', 'name' => 'JALPAIGURI SADAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 252, 'district_id' => 14, 'subdivision_id' => 61, 'schcd' => '191904', 'name' => 'TAMLUK', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 253, 'district_id' => 20, 'subdivision_id' => 51, 'schcd' => '191606', 'name' => 'ULUBERIA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 254, 'district_id' => 14, 'subdivision_id' => 61, 'schcd' => '191905', 'name' => 'SAHID MATANGINI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 188, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191119', 'name' => 'SWARUPNAGAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 189, 'district_id' => 23, 'subdivision_id' => 39, 'schcd' => '191120', 'name' => 'BAGDAH', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 255, 'district_id' => 14, 'subdivision_id' => 61, 'schcd' => '191906', 'name' => 'NANDAKUMAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 256, 'district_id' => 14, 'subdivision_id' => 61, 'schcd' => '191907', 'name' => 'CHANDIPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 257, 'district_id' => 14, 'subdivision_id' => 60, 'schcd' => '191908', 'name' => 'MAHISADAL', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 258, 'district_id' => 14, 'subdivision_id' => 60, 'schcd' => '191909', 'name' => 'NANDIGRAM -II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 259, 'district_id' => 14, 'subdivision_id' => 60, 'schcd' => '191910', 'name' => 'SUTAHATA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 260, 'district_id' => 14, 'subdivision_id' => 60, 'schcd' => '191911', 'name' => 'HALDIA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 261, 'district_id' => 14, 'subdivision_id' => 60, 'schcd' => '191912', 'name' => 'NANDIGRAM -I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 262, 'district_id' => 14, 'subdivision_id' => 58, 'schcd' => '191913', 'name' => 'KHEJURI -II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 263, 'district_id' => 14, 'subdivision_id' => 58, 'schcd' => '191914', 'name' => 'CONTAI -I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 265, 'district_id' => 14, 'subdivision_id' => 58, 'schcd' => '191916', 'name' => 'CONTAI -III', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 266, 'district_id' => 14, 'subdivision_id' => 58, 'schcd' => '191917', 'name' => 'KHEJURI -I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 267, 'district_id' => 14, 'subdivision_id' => 58, 'schcd' => '191918', 'name' => 'RAMNAGAR -I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 268, 'district_id' => 14, 'subdivision_id' => 58, 'schcd' => '191920', 'name' => 'BHAGWANPUR -II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 269, 'district_id' => 14, 'subdivision_id' => 59, 'schcd' => '191921', 'name' => 'EGRA -II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 330, 'district_id' => 4, 'subdivision_id' => 45, 'schcd' => '191318', 'name' => 'SONAMUKHI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 332, 'district_id' => 4, 'subdivision_id' => 44, 'schcd' => '191302', 'name' => 'BANKURA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 334, 'district_id' => 4, 'subdivision_id' => 44, 'schcd' => '191304', 'name' => 'CHHATNA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 335, 'district_id' => 4, 'subdivision_id' => 45, 'schcd' => '191306', 'name' => 'INDAS', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 336, 'district_id' => 4, 'subdivision_id' => 44, 'schcd' => '191313', 'name' => 'ONDA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 24, 'district_id' => 1, 'subdivision_id' => 42, 'schcd' => '191220', 'name' => 'BANSBERIA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 25, 'district_id' => 1, 'subdivision_id' => 41, 'schcd' => '191221', 'name' => 'TARAKESWAR  MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 26, 'district_id' => 1, 'subdivision_id' => 40, 'schcd' => '191222', 'name' => 'ARAMBAGH  MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 28, 'district_id' => 1, 'subdivision_id' => 41, 'schcd' => '191224', 'name' => 'BHADRESWAR  MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 29, 'district_id' => 1, 'subdivision_id' => 41, 'schcd' => '191225', 'name' => 'CHAMPDANI  MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 30, 'district_id' => 1, 'subdivision_id' => 43, 'schcd' => '191226', 'name' => 'BAIDYABATI  MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 31, 'district_id' => 1, 'subdivision_id' => 43, 'schcd' => '191227', 'name' => 'SERAMPORE  MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 33, 'district_id' => 1, 'subdivision_id' => 43, 'schcd' => '191229', 'name' => 'KONNAGAR  MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 34, 'district_id' => 1, 'subdivision_id' => 43, 'schcd' => '191230', 'name' => 'RISHRA  MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 35, 'district_id' => 1, 'subdivision_id' => 43, 'schcd' => '191231', 'name' => 'DANKUNI  MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 84, 'district_id' => 18, 'subdivision_id' => 53, 'schcd' => '191834', 'name' => 'MAHESHTALA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 392, 'district_id' => 5, 'subdivision_id' => 20, 'schcd' => '190715', 'name' => 'LALGOLA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 393, 'district_id' => 5, 'subdivision_id' => 17, 'schcd' => '190716', 'name' => 'RANINAGAR-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 394, 'district_id' => 5, 'subdivision_id' => 17, 'schcd' => '190717', 'name' => 'RANINAGAR-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 395, 'district_id' => 5, 'subdivision_id' => 20, 'schcd' => '190718', 'name' => 'BHAGAWANGOLA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 396, 'district_id' => 5, 'subdivision_id' => 20, 'schcd' => '190719', 'name' => 'BHAGAWANGOLA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 5, 'district_id' => 1, 'subdivision_id' => 41, 'schcd' => '191201', 'name' => 'TARAKESWAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 6, 'district_id' => 1, 'subdivision_id' => 40, 'schcd' => '191202', 'name' => 'KHANAKUL-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 7, 'district_id' => 1, 'subdivision_id' => 43, 'schcd' => '191203', 'name' => 'JANGIPARA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 8, 'district_id' => 1, 'subdivision_id' => 40, 'schcd' => '191204', 'name' => 'PURSURAH', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 10, 'district_id' => 1, 'subdivision_id' => 43, 'schcd' => '191206', 'name' => 'CHANDITALA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 11, 'district_id' => 1, 'subdivision_id' => 43, 'schcd' => '191207', 'name' => 'CHANDITALA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 15, 'district_id' => 1, 'subdivision_id' => 40, 'schcd' => '191211', 'name' => 'GOGHAT-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 16, 'district_id' => 1, 'subdivision_id' => 40, 'schcd' => '191212', 'name' => 'GOGHAT-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 17, 'district_id' => 1, 'subdivision_id' => 43, 'schcd' => '191213', 'name' => 'SERAMPUR-UTTARPARA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 18, 'district_id' => 1, 'subdivision_id' => 42, 'schcd' => '191214', 'name' => 'BALAGARH', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 19, 'district_id' => 1, 'subdivision_id' => 42, 'schcd' => '191215', 'name' => 'CHINSURAH-MOGRA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 20, 'district_id' => 1, 'subdivision_id' => 41, 'schcd' => '191216', 'name' => 'SINGUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 21, 'district_id' => 1, 'subdivision_id' => 42, 'schcd' => '191217', 'name' => 'POLBA-DADPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 22, 'district_id' => 1, 'subdivision_id' => 42, 'schcd' => '191218', 'name' => 'DHANIAKHALI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 9, 'district_id' => 1, 'subdivision_id' => 42, 'schcd' => '191205', 'name' => 'PANDUA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 458, 'district_id' => 9, 'subdivision_id' => 15, 'schcd' => '190610', 'name' => 'RATUA-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 397, 'district_id' => 5, 'subdivision_id' => 18, 'schcd' => '190720', 'name' => 'SAGARDIGHI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 398, 'district_id' => 5, 'subdivision_id' => 18, 'schcd' => '190721', 'name' => 'FARAKKA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 399, 'district_id' => 5, 'subdivision_id' => 18, 'schcd' => '190722', 'name' => 'SAMSERGANJ', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 400, 'district_id' => 5, 'subdivision_id' => 18, 'schcd' => '190723', 'name' => 'SUTI-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 401, 'district_id' => 5, 'subdivision_id' => 18, 'schcd' => '190724', 'name' => 'SUTI-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 402, 'district_id' => 5, 'subdivision_id' => 18, 'schcd' => '190725', 'name' => 'RAGHUNATHGANJ-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 403, 'district_id' => 5, 'subdivision_id' => 18, 'schcd' => '190726', 'name' => 'RAGHUNATHGANJ-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 415, 'district_id' => 22, 'subdivision_id' => 66, 'schcd' => '192002', 'name' => 'KESHPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 416, 'district_id' => 22, 'subdivision_id' => 66, 'schcd' => '192003', 'name' => 'GARHBETA-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 417, 'district_id' => 22, 'subdivision_id' => 66, 'schcd' => '192004', 'name' => 'GARHBETA-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 418, 'district_id' => 22, 'subdivision_id' => 66, 'schcd' => '192005', 'name' => 'GARHBETA-3', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 419, 'district_id' => 22, 'subdivision_id' => 66, 'schcd' => '192006', 'name' => 'SALBONI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 420, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192007', 'name' => 'KHARAGPUR-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 421, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192008', 'name' => 'KHARAGPUR-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 422, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192009', 'name' => 'NARAYANGARH', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 423, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192010', 'name' => 'SABONG', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 424, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192011', 'name' => 'DEBRA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 425, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192012', 'name' => 'PINGLA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 426, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192013', 'name' => 'MOHANPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 427, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192014', 'name' => 'DANTAN-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 428, 'district_id' => 22, 'subdivision_id' => 64, 'schcd' => '192015', 'name' => 'DANTAN-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 430, 'district_id' => 22, 'subdivision_id' => 65, 'schcd' => '192018', 'name' => 'CHANDRAKONA-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 431, 'district_id' => 22, 'subdivision_id' => 65, 'schcd' => '192019', 'name' => 'CHANDRAKONA-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 432, 'district_id' => 22, 'subdivision_id' => 65, 'schcd' => '192025', 'name' => 'GHATAL', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 433, 'district_id' => 22, 'subdivision_id' => 65, 'schcd' => '192028', 'name' => 'DASPUR-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 434, 'district_id' => 22, 'subdivision_id' => 65, 'schcd' => '192029', 'name' => 'DASPUR-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 460, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190605', 'name' => 'KALIACHAK-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 462, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190606', 'name' => 'KALIACHAK-3', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 463, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190613', 'name' => 'BAMONGOLA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 231, 'district_id' => 2, 'subdivision_id' => 4, 'schcd' => '190203', 'name' => 'DHUPGURI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 464, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190615', 'name' => 'GAZOLE', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 465, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190608', 'name' => 'OLD MALDA(BLOCK)', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 466, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190601', 'name' => 'ENGLISH BAZAR(BLOCK)', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 468, 'district_id' => 9, 'subdivision_id' => 15, 'schcd' => '190612', 'name' => 'CHANCHAL-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 469, 'district_id' => 9, 'subdivision_id' => 15, 'schcd' => '190611', 'name' => 'CHANCHAL-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 470, 'district_id' => 9, 'subdivision_id' => 15, 'schcd' => '190602', 'name' => 'HARISHCHANDRAPUR-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 471, 'district_id' => 9, 'subdivision_id' => 15, 'schcd' => '190609', 'name' => 'RATUA-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 472, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190607', 'name' => 'MANIKCHAK', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 474, 'district_id' => 12, 'subdivision_id' => 67, 'schcd' => '192101', 'name' => 'MATIGARA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 475, 'district_id' => 12, 'subdivision_id' => 67, 'schcd' => '192102', 'name' => 'KHORIBARI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 476, 'district_id' => 12, 'subdivision_id' => 67, 'schcd' => '192103', 'name' => 'NAXALBARI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 477, 'district_id' => 12, 'subdivision_id' => 67, 'schcd' => '192104', 'name' => 'PHANSIDEWA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            // [ 'id' => 479, 'district_id' => 13, 'subdivision_id' => 71, 'schcd' => '191401', 'name' => 'ARSHA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 480, 'district_id' => 13, 'subdivision_id' => 49, 'schcd' => '191402', 'name' => 'BAGHMUNDI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 481, 'district_id' => 10, 'subdivision_id' => 12, 'schcd' => '190401', 'name' => 'HEMTABAD', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 482, 'district_id' => 10, 'subdivision_id' => 12, 'schcd' => '190402', 'name' => 'KALIYAGANJ', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 483, 'district_id' => 10, 'subdivision_id' => 12, 'schcd' => '190403', 'name' => 'RAIGANJ', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 484, 'district_id' => 10, 'subdivision_id' => 11, 'schcd' => '190405', 'name' => 'GOALPOKHER - I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 485, 'district_id' => 10, 'subdivision_id' => 11, 'schcd' => '190406', 'name' => 'CHOPRA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 486, 'district_id' => 10, 'subdivision_id' => 11, 'schcd' => '190407', 'name' => 'KARANDIGHI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 487, 'district_id' => 10, 'subdivision_id' => 11, 'schcd' => '190408', 'name' => 'ISLAMPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 488, 'district_id' => 10, 'subdivision_id' => 12, 'schcd' => '190409', 'name' => 'ITAHAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            // [ 'id' => 493, 'district_id' => 13, 'subdivision_id' => 71, 'schcd' => '191403', 'name' => 'BALARAMPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 494, 'district_id' => 13, 'subdivision_id' => 48, 'schcd' => '191404', 'name' => 'BANDWAN', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 385, 'district_id' => 5, 'subdivision_id' => 21, 'schcd' => '190708', 'name' => 'NOWDA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 386, 'district_id' => 5, 'subdivision_id' => 21, 'schcd' => '190709', 'name' => 'HARIHARPARA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 387, 'district_id' => 5, 'subdivision_id' => 17, 'schcd' => '190710', 'name' => 'DOMKAL', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 388, 'district_id' => 5, 'subdivision_id' => 21, 'schcd' => '190711', 'name' => 'BERHAMPORE', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 389, 'district_id' => 5, 'subdivision_id' => 17, 'schcd' => '190712', 'name' => 'JALANGI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 390, 'district_id' => 5, 'subdivision_id' => 20, 'schcd' => '190713', 'name' => 'MURSHIDABAD-JIAGANJ (M.J)', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 391, 'district_id' => 5, 'subdivision_id' => 20, 'schcd' => '190714', 'name' => 'NABAGRAM', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 343, 'district_id' => 3, 'subdivision_id' => 29, 'schcd' => '192507', 'name' => 'GALSI-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 344, 'district_id' => 3, 'subdivision_id' => 30, 'schcd' => '192508', 'name' => 'JAMALPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 345, 'district_id' => 3, 'subdivision_id' => 27, 'schcd' => '192509', 'name' => 'KALNA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 347, 'district_id' => 3, 'subdivision_id' => 28, 'schcd' => '192511', 'name' => 'KATWA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 348, 'district_id' => 3, 'subdivision_id' => 28, 'schcd' => '192512', 'name' => 'KATWA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 354, 'district_id' => 3, 'subdivision_id' => 28, 'schcd' => '192518', 'name' => 'MONGALKOTE', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 356, 'district_id' => 3, 'subdivision_id' => 27, 'schcd' => '192520', 'name' => 'PURBASTHALI-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 357, 'district_id' => 3, 'subdivision_id' => 27, 'schcd' => '192521', 'name' => 'PURBASTHALI-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 358, 'district_id' => 3, 'subdivision_id' => 30, 'schcd' => '192522', 'name' => 'RAINA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 353, 'district_id' => 3, 'subdivision_id' => 30, 'schcd' => '192517', 'name' => 'MEMARI-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 352, 'district_id' => 3, 'subdivision_id' => 30, 'schcd' => '192516', 'name' => 'MEMARI-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 350, 'district_id' => 3, 'subdivision_id' => 28, 'schcd' => '192514', 'name' => 'KETUGRAM-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 349, 'district_id' => 3, 'subdivision_id' => 28, 'schcd' => '192513', 'name' => 'KETUGRAM-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 351, 'district_id' => 3, 'subdivision_id' => 30, 'schcd' => '192515', 'name' => 'KHANDOGHOSH', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 346, 'district_id' => 3, 'subdivision_id' => 27, 'schcd' => '192510', 'name' => 'KALNA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 359, 'district_id' => 3, 'subdivision_id' => 30, 'schcd' => '192523', 'name' => 'RAINA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 355, 'district_id' => 3, 'subdivision_id' => 27, 'schcd' => '192519', 'name' => 'MONTESWAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 3, 'district_id' => 24, 'subdivision_id' => 2, 'schcd' => '192403', 'name' => 'KALIMPONG-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 412, 'district_id' => 8, 'subdivision_id' => 63, 'schcd' => '192302', 'name' => 'JAMBONI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 413, 'district_id' => 8, 'subdivision_id' => 63, 'schcd' => '192303', 'name' => 'BINPUR-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 414, 'district_id' => 8, 'subdivision_id' => 63, 'schcd' => '192304', 'name' => 'BINPUR-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 443, 'district_id' => 8, 'subdivision_id' => 63, 'schcd' => '192305', 'name' => 'SANKRAIL', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 444, 'district_id' => 8, 'subdivision_id' => 63, 'schcd' => '192306', 'name' => 'NAYAGRAM', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 1, 'district_id' => 24, 'subdivision_id' => 4, 'schcd' => '192401', 'name' => 'GORUBATHAN', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 2, 'district_id' => 24, 'subdivision_id' => 4, 'schcd' => '192402', 'name' => 'KALIMPONG-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 12, 'district_id' => 1, 'subdivision_id' => 40, 'schcd' => '191208', 'name' => 'ARAMBAGH', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 13, 'district_id' => 1, 'subdivision_id' => 41, 'schcd' => '191209', 'name' => 'HARIPAL', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 14, 'district_id' => 1, 'subdivision_id' => 40, 'schcd' => '191210', 'name' => 'KHANAKUL-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 456, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190614', 'name' => 'HABIBPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 457, 'district_id' => 9, 'subdivision_id' => 15, 'schcd' => '190603', 'name' => 'HARISHCHANDRAPUR-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 459, 'district_id' => 9, 'subdivision_id' => 16, 'schcd' => '190604', 'name' => 'KALIACHAK-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 495, 'district_id' => 13, 'subdivision_id' => 48, 'schcd' => '191405', 'name' => 'BARABAZAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            // [ 'id' => 496, 'district_id' => 13, 'subdivision_id' => 71, 'schcd' => '191406', 'name' => 'HURA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 497, 'district_id' => 13, 'subdivision_id' => 49, 'schcd' => '191407', 'name' => 'JHALDA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 498, 'district_id' => 13, 'subdivision_id' => 49, 'schcd' => '191408', 'name' => 'JHALDA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 499, 'district_id' => 13, 'subdivision_id' => 49, 'schcd' => '191409', 'name' => 'JOYPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 500, 'district_id' => 13, 'subdivision_id' => 47, 'schcd' => '191410', 'name' => 'KASHIPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 501, 'district_id' => 13, 'subdivision_id' => 48, 'schcd' => '191411', 'name' => 'MANBAZAR-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 502, 'district_id' => 13, 'subdivision_id' => 48, 'schcd' => '191412', 'name' => 'MANBAZAR-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 503, 'district_id' => 13, 'subdivision_id' => 47, 'schcd' => '191413', 'name' => 'NETURIA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 504, 'district_id' => 13, 'subdivision_id' => 47, 'schcd' => '191414', 'name' => 'PARA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 505, 'district_id' => 13, 'subdivision_id' => 48, 'schcd' => '191415', 'name' => 'PUNCHA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            // [ 'id' => 506, 'district_id' => 13, 'subdivision_id' => 71, 'schcd' => '191416', 'name' => 'PURULIA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            // [ 'id' => 507, 'district_id' => 13, 'subdivision_id' => 71, 'schcd' => '191417', 'name' => 'PURULIA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 508, 'district_id' => 13, 'subdivision_id' => 47, 'schcd' => '191418', 'name' => 'RAGHUNATHPUR-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 448, 'district_id' => 21, 'subdivision_id' => 1, 'schcd' => '190129', 'name' => 'DARJEELING PULBAZAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 450, 'district_id' => 21, 'subdivision_id' => 3, 'schcd' => '190131', 'name' => 'KURSEONG', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 451, 'district_id' => 21, 'subdivision_id' => 3, 'schcd' => '190132', 'name' => 'MIRIK', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 452, 'district_id' => 21, 'subdivision_id' => 1, 'schcd' => '190133', 'name' => 'JOREBUNGLOW SUKHIA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 518, 'district_id' => 6, 'subdivision_id' => 10, 'schcd' => '190305', 'name' => 'TUFANGANJ-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 519, 'district_id' => 6, 'subdivision_id' => 9, 'schcd' => '190306', 'name' => 'MEKHLIGANJ', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 520, 'district_id' => 6, 'subdivision_id' => 9, 'schcd' => '190307', 'name' => 'HALDIBARI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 521, 'district_id' => 6, 'subdivision_id' => 7, 'schcd' => '190308', 'name' => 'COOCH BEHAR-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 522, 'district_id' => 6, 'subdivision_id' => 7, 'schcd' => '190309', 'name' => 'COOCH BEHAR-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 523, 'district_id' => 6, 'subdivision_id' => 8, 'schcd' => '190310', 'name' => 'SITALKUCHI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 524, 'district_id' => 6, 'subdivision_id' => 8, 'schcd' => '190311', 'name' => 'MATHABHANGA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 525, 'district_id' => 6, 'subdivision_id' => 8, 'schcd' => '190312', 'name' => 'MATHABHANGA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 445, 'district_id' => 8, 'subdivision_id' => 63, 'schcd' => '192307', 'name' => 'GOPIBALLAVPUR-1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 367, 'district_id' => 7, 'subdivision_id' => 14, 'schcd' => '190502', 'name' => 'HARIRAMPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 368, 'district_id' => 7, 'subdivision_id' => 14, 'schcd' => '190503', 'name' => 'GANGARAMPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 369, 'district_id' => 7, 'subdivision_id' => 13, 'schcd' => '190504', 'name' => 'KUMARGANJ', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 373, 'district_id' => 7, 'subdivision_id' => 14, 'schcd' => '190508', 'name' => 'KUSHMONDI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 376, 'district_id' => 4, 'subdivision_id' => 46, 'schcd' => '191320', 'name' => 'SIMLAPAL', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 377, 'district_id' => 4, 'subdivision_id' => 44, 'schcd' => '191319', 'name' => 'SALTORA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 378, 'district_id' => 5, 'subdivision_id' => 19, 'schcd' => '190701', 'name' => 'KANDI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 379, 'district_id' => 5, 'subdivision_id' => 19, 'schcd' => '190702', 'name' => 'BHARATPUR-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 381, 'district_id' => 5, 'subdivision_id' => 19, 'schcd' => '190704', 'name' => 'BARWAN', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 447, 'district_id' => 8, 'subdivision_id' => 63, 'schcd' => '192309', 'name' => 'GOPIBALLAVPUR-2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 442, 'district_id' => 8, 'subdivision_id' => 63, 'schcd' => '192301', 'name' => 'JHARGRAM', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 32, 'district_id' => 1, 'subdivision_id' => 43, 'schcd' => '191228', 'name' => 'UTTARPARA KOTRANG', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 241, 'district_id' => 2, 'subdivision_id' => 4, 'schcd' => '190217', 'name' => 'SILIGURI MUNICIPALITY CORPORATION', 'type' => 'C', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 236, 'district_id' => 2, 'subdivision_id' => 5, 'schcd' => '190212', 'name' => 'NAGRAKATA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 234, 'district_id' => 2, 'subdivision_id' => 5, 'schcd' => '190210', 'name' => 'MATELLI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 175, 'district_id' => 25, 'subdivision_id' => 26, 'schcd' => '192609', 'name' => 'DURGAPUR MUNICIPAL CORPORATION', 'type' => 'C', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 27, 'district_id' => 1, 'subdivision_id' => 41, 'schcd' => '191223', 'name' => 'CHANDANNAGORE CORPORATION', 'type' => 'C', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 110, 'district_id' => 17, 'subdivision_id' => 31, 'schcd' => '191025', 'name' => 'CHAKDAH MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 78, 'district_id' => 18, 'subdivision_id' => 54, 'schcd' => '191820', 'name' => 'MANDIRBAZAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 79, 'district_id' => 18, 'subdivision_id' => 56, 'schcd' => '191825', 'name' => 'NAMKHANA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 80, 'district_id' => 18, 'subdivision_id' => 54, 'schcd' => '191813', 'name' => 'FALTA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 81, 'district_id' => 18, 'subdivision_id' => 53, 'schcd' => '191808', 'name' => 'BUDGE BUDGE - 2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 82, 'district_id' => 18, 'subdivision_id' => 56, 'schcd' => '191817', 'name' => 'KAKDWIP', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 83, 'district_id' => 18, 'subdivision_id' => 54, 'schcd' => '191811', 'name' => 'DIAMOND HARBOUR - 1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 85, 'district_id' => 18, 'subdivision_id' => 54, 'schcd' => '191821', 'name' => 'MAGRAHAT - 1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 177, 'district_id' => 15, 'subdivision_id' => 68, 'schcd' => '192201', 'name' => 'ALIPURDUAR-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 178, 'district_id' => 15, 'subdivision_id' => 68, 'schcd' => '192202', 'name' => 'ALIPURDUAR-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 179, 'district_id' => 15, 'subdivision_id' => 68, 'schcd' => '192204', 'name' => 'FALAKATA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 67, 'district_id' => 25, 'subdivision_id' => 25, 'schcd' => '192610', 'name' => 'ASANSOL MUNICIPAL CORPORATION', 'type' => 'C', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 360, 'district_id' => 3, 'subdivision_id' => 29, 'schcd' => '192524', 'name' => 'BURDWAN MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 361, 'district_id' => 3, 'subdivision_id' => 28, 'schcd' => '192525', 'name' => 'DAINHAT MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 4, 'district_id' => 24, 'subdivision_id' => 2, 'schcd' => '192404', 'name' => 'KALIMPONG MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 86, 'district_id' => 18, 'subdivision_id' => 55, 'schcd' => '191802', 'name' => 'BASANTI', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 180, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191111', 'name' => 'BASIRHAT - I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 181, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191112', 'name' => 'BASIRHAT - II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 182, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191113', 'name' => 'HAROA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 87, 'district_id' => 18, 'subdivision_id' => 53, 'schcd' => '191803', 'name' => 'BISHNUPUR - 1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 88, 'district_id' => 18, 'subdivision_id' => 53, 'schcd' => '191804', 'name' => 'BISHNUPUR - 2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 89, 'district_id' => 18, 'subdivision_id' => 57, 'schcd' => '191805', 'name' => 'BHANGORE - 1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 90, 'district_id' => 18, 'subdivision_id' => 57, 'schcd' => '191806', 'name' => 'BHANGORE - 2', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 91, 'district_id' => 18, 'subdivision_id' => 53, 'schcd' => '191807', 'name' => 'BUDGE BUDGE - 1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 92, 'district_id' => 18, 'subdivision_id' => 55, 'schcd' => '191809', 'name' => 'CANNING - 1', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 102, 'district_id' => 18, 'subdivision_id' => 53, 'schcd' => '191831', 'name' => 'BUDGE BUDGE MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 103, 'district_id' => 18, 'subdivision_id' => 57, 'schcd' => '191833', 'name' => 'JOYNAGAR MAZILPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 183, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191114', 'name' => 'HASNABAD', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 184, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191115', 'name' => 'HINGALGANJ', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 185, 'district_id' => 23, 'subdivision_id' => 37, 'schcd' => '191116', 'name' => 'MINAKHAN', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 197, 'district_id' => 23, 'subdivision_id' => 35, 'schcd' => '191128', 'name' => 'GOBORDANGA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 221, 'district_id' => 19, 'subdivision_id' => 22, 'schcd' => '190820', 'name' => 'BOLPUR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 272, 'district_id' => 14, 'subdivision_id' => 59, 'schcd' => '191924', 'name' => 'PATASHPUR -I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 273, 'district_id' => 14, 'subdivision_id' => 59, 'schcd' => '191925', 'name' => 'PATASHPUR -II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 278, 'district_id' => 14, 'subdivision_id' => 58, 'schcd' => '191930', 'name' => 'RAMNAGAR -II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 284, 'district_id' => 20, 'subdivision_id' => 51, 'schcd' => '191611', 'name' => 'SHYAMPUR-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 190, 'district_id' => 23, 'subdivision_id' => 39, 'schcd' => '191121', 'name' => 'BONGAON', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 191, 'district_id' => 23, 'subdivision_id' => 39, 'schcd' => '191122', 'name' => 'GAIGHATA', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 203, 'district_id' => 19, 'subdivision_id' => 22, 'schcd' => '190802', 'name' => 'ILLAMBAZAR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 204, 'district_id' => 19, 'subdivision_id' => 22, 'schcd' => '190803', 'name' => 'NANOOR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 205, 'district_id' => 19, 'subdivision_id' => 22, 'schcd' => '190804', 'name' => 'LABPUR', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 366, 'district_id' => 4, 'subdivision_id' => 46, 'schcd' => '191317', 'name' => 'SARENGA [RAIPUR-II]', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 380, 'district_id' => 5, 'subdivision_id' => 19, 'schcd' => '190703', 'name' => 'BHARATPUR-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 382, 'district_id' => 5, 'subdivision_id' => 19, 'schcd' => '190705', 'name' => 'KHARGRAM', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 383, 'district_id' => 5, 'subdivision_id' => 21, 'schcd' => '190706', 'name' => 'BELDANGA-I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 384, 'district_id' => 5, 'subdivision_id' => 21, 'schcd' => '190707', 'name' => 'BELDANGA-II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 164, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191108', 'name' => 'BARRACKPORE - I', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 165, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191109', 'name' => 'BARRACKPORE - II', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 198, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191129', 'name' => 'HALISAHAR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 199, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191130', 'name' => 'KANCHRAPARA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 200, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191131', 'name' => 'NAIHATI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 201, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191132', 'name' => 'BHATPARA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 202, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191133', 'name' => 'GARULIA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 291, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191134', 'name' => 'TITAGARH MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 292, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191135', 'name' => 'BARRACKPORE MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 293, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191136', 'name' => 'NORTH BARRACKPORE MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 295, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191138', 'name' => 'KHARDAHA MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 296, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191139', 'name' => 'PANIHATI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 297, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191140', 'name' => 'KAMARHATTI MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 298, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191141', 'name' => 'BARANAGAR MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 299, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191142', 'name' => 'DUM DUM MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 300, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191143', 'name' => 'NORTH DUM DUM MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 301, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191144', 'name' => 'SOUTH DUM DUM MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 302, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191145', 'name' => 'NEW BARRACKPORE MUNICIPALITY', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 307, 'district_id' => 99, 'subdivision_id' => 38, 'schcd' => '191150', 'name' => 'BIDHANNAGAR MUNICIPAL CORPORATION', 'type' => 'C', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 294, 'district_id' => 99, 'subdivision_id' => 36, 'schcd' => '191137', 'name' => 'BARRACKPORE CANTONMENT BOARD', 'type' => 'M', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'id' => 264, 'district_id' => 14, 'subdivision_id' => 58, 'schcd' => '191915', 'name' => 'DESHAPRAN', 'type' => 'B', 'status' => 1, 'created_at' => $now, 'updated_at' => $now ],
        ];

        DB::table('bs_block_munc_corp_master')->insert($data);
    }
}
